version: "3.8"
services:
  db:
    image: postgres:latest
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - db-postgres-data:/var/lib/postgresql@17/data:rw
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql@17/data:rw

  backend:
    # set volume to have changes made locally available in uvicorn localhost:8000/docs (run in container)
    volumes:
      - ./src/backend/app:/opt/backend/backend/app
      - ./src/backend/logs:/opt/backend/backend/logs
      - ./data/models:/opt/backend/backend/data/models
    image: kesava89/bundestag-backend:latest
    environment:
      - POSTGRES_SERVER=${POSTGRES_SERVER}
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:80"

volumes:
  db-postgres-data:
