GERMAN_ARTICLES = set(
    [
        # Nominative
        'Der',
        'Die',
        'Das',
        'Ein',
        'Eine',
        # Accusative
        'Den',
        'Die',
        'Das',
        'Einen',
        'Eine',
        'Ein',
        # Dative
        'Dem',
        'Der',
        'Dem',
        'Einem',
        'Einer',
        'Einem',
        # Genitive
        'Des',
        'Der',
        'Des',
        'Eines',
        'Einer',
        'Eines',
        # Plural forms
        'Die',
        'Die',
        'Die',
        'Keine',
        # Special forms
        'Zur',
        'Zum',
        'Zur',
        'Zur',
        'Zu den',
        'Zu der',
        'Zu dem',
        'Zu der',
        'Dessen',
        'Deren',
        # Common prepositions
        'Mit',
        'Ohne',
        'An',
        'Auf',
        'In',
        'Unter',
        'Über',
        'Vor',
        'Hinter',
        'Neben',
        'Zwischen',
        'Bei',
        'Nach',
        'Seit',
        'Während',
        'Gegenüber',
        # Interrogative pronouns
        'Wer',
        'Was',
        'Wessen',
        'Wem',
        'Wen',
        # Demonstrative pronouns
        'Dieser',
        'Diese',
        'Dieses',
        'Diese',
        'Dieses',
        'Dieser',
        'Diesen',
        'Dieser',
        'Diesem',
        'Diesem',
        # Relative pronouns
        'Der',
        'Die',
        'Das',
        'Denen',
        # Conjunctions
        'Und',
        'Oder',
        'Aber',
        'Denn',
        # Präpositionen (Prepositions)
        'Mit',
        'Ohne',
        'An',
        'Auf',
        'In',
        'Unter',
        'Über',
        'Vor',
        'Hinter',
        'Neben',
        'Zwischen',
        'Bei',
        'Nach',
        'Seit',
        'Während',
        'Gegenüber',
        'Außerhalb',
        'Innerhalb',
        'Entlang',
        'Durch',
        'Für',
        'Wegen',
        'Trotz',
        'Bis',
        'Zu',
        # Personal pronouns
        'Ich',
        'Du',
        'Er',
        'Sie',
        'Es',
        'Wir',
        'Ihr',
        'Sie',
        'Sie',
        # Reflexive pronouns
        'Mich',
        'Dich',
        'Sich',
        'Uns',
        'Euch',
        'Sich',
        'Sich',
        # Possessive pronouns
        'Mein',
        'Dein',
        'Sein',
        'Ihr',
        'Sein',
        'Unser',
        'Euer',
        'Ihr',
        'Ihr',
        'Meiner',
        'Deiner',
        'Seiner',
        'Ihrer',
        'Seiner',
        'Unser',
        'Euer',
        'Ihrer',
        'Ihrer',
        'Meins',
        'Deins',
        'Seins',
        'Ihres',
        'Seins',
        'Unser',
        'Euer',
        'Ihres',
        'Ihres',
        'Meinem',
        'Deinem',
        'Seinem',
        'Ihrem',
        'Seinem',
        'Unserem',
        'Eurem',
        'Ihrem',
        'Ihrem',
        'Meinen',
        'Deinen',
        'Seinen',
        'Ihren',
        'Seinen',
        'Unseren',
        'Euren',
        'Ihren',
        'Ihren',
        # Demonstrative pronouns
        'Dieser',
        'Diese',
        'Dieses',
        'Jener',
        'Jene',
        'Jenes',
        # Relative pronouns
        'Der',
        'Die',
        'Das',
        'Denen',
        'Welcher',
        'Welche',
        'Welches',
        # Interrogative pronouns
        'Wer',
        'Wen',
        'Wem',
        'Wessen',
        'Was',
        'Welcher',
        'Welche',
        'Welches',
        # Indefinite pronounss
        'Alle',
        'Viele',
        'Einige',
        'Jeder',
        'Jede',
        'Jedes',
        'Manche',
        'Irgendein',
        'Irgendeine',
        'Irgendein',
    ]
)
