"""Add mandate timetable

Revision ID: 86512f637f1a
Revises: 168b8f28461f
Create Date: 2023-12-10 23:54:31.186602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86512f637f1a'
down_revision: Union[str, None] = 'f8c93790f568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'mandate',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('wahlperiode', sa.Integer(), nullable=False),
        sa.Column('anzahl_stimmberechtigt', sa.Integer(), nullable=False),
        sa.Column('date_from', sa.Date(), nullable=False),
        sa.Column('date_to', sa.Date(), nullable=True),
        sa.Column('comment', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mandate')
    # ### end Alembic commands ###
