"""Fix fundstelle ids and add vorgangsposition table

Revision ID: 94b6ec6dbc4d
Revises: 953503180a23
Create Date: 2023-11-25 21:30:31.865455

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '94b6ec6dbc4d'
down_revision: Union[str, None] = '953503180a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_column(
        'drucksache',
        'date',
        schema='dip',
    )

    op.alter_column(
        'drucksache',
        'datum',
        type_=sa.Date(),
        schema='dip',
        postgresql_using='datum::date',
    )
    op.alter_column(
        'drucksache',
        'aktualisiert',
        type_=sa.DateTime(),
        schema='dip',
        postgresql_using='aktualisiert::timestamp',
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'vorgangsposition',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('vorgangsposition', sa.String(), nullable=False),
        sa.Column(
            'zuordnung',
            postgresql.ENUM(name='zuordnung', create_type=False),
            nullable=False,
        ),
        sa.Column('gang', sa.Boolean(), nullable=False),
        sa.Column('fortsetzung', sa.Boolean(), nullable=False),
        sa.Column('nachtrag', sa.Boolean(), nullable=False),
        sa.Column('vorgangstyp', sa.String(), nullable=False),
        sa.Column('typ', sa.Enum('Vorgangsposition', name='vorgangspositiontyp'), nullable=False),
        sa.Column('titel', sa.String(), nullable=False),
        sa.Column(
            'dokumentart',
            postgresql.ENUM(name='dokumentart', create_type=False),
            nullable=False,
        ),
        sa.Column('vorgang_id', sa.Integer(), nullable=False),
        sa.Column('datum', sa.Date(), nullable=False),
        sa.Column('aktualisiert', sa.DateTime(), nullable=False),
        sa.Column('aktivitaet_anzahl', sa.Integer(), nullable=False),
        sa.Column('ratsdok', sa.String(), nullable=True),
        sa.Column('kom', sa.String(), nullable=True),
        sa.Column('sek', sa.String(), nullable=True),
        sa.Column('abstract', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        schema='dip',
    )

    op.alter_column(
        'fundstelle',
        'drucksache_id',
        nullable=True,
        schema='dip',
    )

    op.add_column(
        'fundstelle',
        sa.Column('vorgangsposition_id', sa.Integer(), nullable=True),
        schema='dip',
    )

    op.create_foreign_key(
        'fundstelle_vorgangsposition_id_fkey',
        'fundstelle',
        'vorgangsposition',
        ['vorgangsposition_id'],
        ['id'],
        source_schema='dip',
        referent_schema='dip',
    )

    op.alter_column(
        'ressort',
        'drucksache_id',
        nullable=True,
        schema='dip',
    )

    op.add_column(
        'ressort',
        sa.Column('vorgangsposition_id', sa.Integer(), nullable=True),
        schema='dip',
    )

    op.create_foreign_key(
        'ressort_vorgangsposition_id_fkey',
        'ressort',
        'vorgangsposition',
        ['vorgangsposition_id'],
        ['id'],
        source_schema='dip',
        referent_schema='dip',
    )

    op.alter_column(
        'urheber',
        'drucksache_id',
        nullable=True,
        schema='dip',
    )

    op.add_column(
        'urheber',
        sa.Column('vorgangsposition_id', sa.Integer(), nullable=True),
        schema='dip',
    )

    op.create_foreign_key(
        'urheber_vorgangsposition_id_fkey',
        'urheber',
        'vorgangsposition',
        ['vorgangsposition_id'],
        ['id'],
        source_schema='dip',
        referent_schema='dip',
    )

    op.create_table(
        'aktivitaet_anzeige',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('vorgangsposition_id', sa.Integer(), nullable=False),
        sa.Column('aktivitaetsart', sa.String(), nullable=False),
        sa.Column('titel', sa.String(), nullable=False),
        sa.Column('pdf_url', sa.String(), nullable=True),
        sa.Column('seite', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(
            ['vorgangsposition_id'],
            ['dip.vorgangsposition.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        schema='dip',
    )

    op.create_table(
        'beschlussfassung',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('vorgangsposition_id', sa.Integer(), nullable=False),
        sa.Column('beschlusstenor', sa.String(), nullable=False),
        sa.Column('seite', sa.String(), nullable=True),
        sa.Column(
            'abstimmungsart',
            sa.Enum(
                'Abstimmung_durch_Aufruf_der_Länder',
                'Geheime_Wahl',
                'Hammelsprung',
                'Namentliche_Abstimmung',
                'Verhältniswahl',
                name='abstimmungsart',
            ),
            nullable=True,
        ),
        sa.Column('abstimm_ergebnis_bemerkung', sa.String(), nullable=True),
        sa.Column('grundlage', sa.String(), nullable=True),
        sa.Column('dokumentnummer', sa.String(), nullable=True),
        sa.Column(
            'mehrheit',
            sa.Enum('Absolute_Mehrheit', 'Zweidrittelmehrheit', name='mehrheit'),
            nullable=True,
        ),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(
            ['vorgangsposition_id'],
            ['dip.vorgangsposition.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        schema='dip',
    )

    op.create_table(
        'ueberweisung',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('vorgangsposition_id', sa.Integer(), nullable=False),
        sa.Column('ausschuss', sa.String(), nullable=False),
        sa.Column('ausschuss_kuerzel', sa.String(), nullable=False),
        sa.Column('federfuehrung', sa.Boolean(), nullable=False),
        sa.Column('ueberweisungsart', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(
            ['vorgangsposition_id'],
            ['dip.vorgangsposition.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        schema='dip',
    )

    op.create_table(
        'vorgangspositionbezug',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('vorgangsposition_id', sa.Integer(), nullable=False),
        sa.Column('from_vorgang_id', sa.Integer(), nullable=False),
        sa.Column('to_vorgang_id', sa.Integer(), nullable=False),
        sa.Column('titel', sa.String(), nullable=False),
        sa.Column('vorgangstyp', sa.String(), nullable=False),
        sa.Column('vorgangsposition', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(
            ['vorgangsposition_id'],
            ['dip.vorgangsposition.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        schema='dip',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('vorgangspositionbezug', schema='dip')
    op.drop_table('ueberweisung', schema='dip')
    op.drop_table('beschlussfassung', schema='dip')

    sa.Enum(
        'Abstimmung_durch_Aufruf_der_Länder',
        'Geheime_Wahl',
        'Hammelsprung',
        'Namentliche_Abstimmung',
        'Verhältniswahl',
        name='abstimmungsart',
    ).drop(op.get_bind(), checkfirst=False)

    sa.Enum('Absolute_Mehrheit', 'Zweidrittelmehrheit', name='mehrheit').drop(
        op.get_bind(), checkfirst=False
    )
    op.drop_table('aktivitaet_anzeige', schema='dip')

    op.drop_constraint(
        'urheber_vorgangsposition_id_fkey',
        'urheber',
        schema='dip',
    )

    op.drop_column(
        'urheber',
        'vorgangsposition_id',
        schema='dip',
    )

    op.execute("DELETE FROM dip.urheber WHERE drucksache_id IS NULL;")

    op.alter_column(
        'urheber',
        'drucksache_id',
        nullable=False,
        schema='dip',
    )

    op.drop_constraint(
        'ressort_vorgangsposition_id_fkey',
        'ressort',
        schema='dip',
    )

    op.drop_column(
        'ressort',
        'vorgangsposition_id',
        schema='dip',
    )

    op.execute("DELETE FROM dip.ressort WHERE drucksache_id IS NULL;")

    op.alter_column(
        'ressort',
        'drucksache_id',
        nullable=False,
        schema='dip',
    )

    op.drop_constraint(
        'fundstelle_vorgangsposition_id_fkey',
        'fundstelle',
        schema='dip',
    )

    op.drop_column(
        'fundstelle',
        'vorgangsposition_id',
        schema='dip',
    )

    op.execute("DELETE FROM dip.fundstelle WHERE drucksache_id IS NULL;")

    op.alter_column(
        'fundstelle',
        'drucksache_id',
        nullable=False,
        schema='dip',
    )

    op.drop_table('vorgangsposition', schema='dip')

    sa.Enum('Vorgangsposition', name='vorgangspositiontyp').drop(op.get_bind(), checkfirst=False)

    op.alter_column(
        'drucksache',
        'datum',
        type_=sa.Text(),
        schema='dip',
    )
    op.alter_column(
        'drucksache',
        'aktualisiert',
        type_=sa.Text(),
        schema='dip',
    )
    op.add_column(
        'drucksache',
        column=sa.Column(
            'date',
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
        schema='dip',
    )

    # ### end Alembic commands ###
