"""Add vorgang tables

Revision ID: 953503180a23
Revises: a570b683d689
Create Date: 2023-11-25 18:32:12.800616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '953503180a23'
down_revision: Union[str, None] = 'a570b683d689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'vorgang',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('typ', sa.Enum('Vorgang', name='vorgangtyp'), nullable=False),
        sa.Column('beratungsstand', sa.String(), nullable=True),
        sa.Column('vorgangstyp', sa.String(), nullable=False),
        sa.Column('wahlperiode', sa.Integer(), nullable=False),
        sa.Column('initiative', postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column('datum', sa.Date(), nullable=True),
        sa.Column('aktualisiert', sa.DateTime(), nullable=False),
        sa.Column('titel', sa.String(), nullable=False),
        sa.Column('abstract', sa.String(), nullable=True),
        sa.Column('sachgebiet', postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column('gesta', postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column('zustimmungsbeduerftigkeit', postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column('kom', sa.String(), nullable=True),
        sa.Column('ratsdok', sa.String(), nullable=True),
        sa.Column('archiv', sa.String(), nullable=True),
        sa.Column('mitteilung', sa.String(), nullable=True),
        sa.Column('sek', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        schema='dip',
    )
    op.create_table(
        'inkrafttreten',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('vorgang_id', sa.Integer(), nullable=False),
        sa.Column('datum', sa.Date(), nullable=False),
        sa.Column('erlaeuterung', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(
            ['vorgang_id'],
            ['dip.vorgang.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        schema='dip',
    )
    op.create_table(
        'verkuendung',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('vorgang_id', sa.Integer(), nullable=False),
        sa.Column('jahrgang', sa.String(), nullable=True),
        sa.Column('heftnummer', sa.String(), nullable=True),
        sa.Column('seite', sa.String(), nullable=True),
        sa.Column('ausfertigungsdatum', sa.Date(), nullable=False),
        sa.Column('verkuendungsdatum', sa.Date(), nullable=False),
        sa.Column('rubrik_nr', sa.String(), nullable=True),
        sa.Column('einleitungstext', sa.String(), nullable=True),
        sa.Column('verkuendungsblatt_bezeichnung', sa.String(), nullable=True),
        sa.Column('verkuendungsblatt_kuerzel', sa.String(), nullable=True),
        sa.Column('fundstelle', sa.String(), nullable=False),
        sa.Column('pdf_url', sa.String(), nullable=True),
        sa.Column('titel', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(
            ['vorgang_id'],
            ['dip.vorgang.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        schema='dip',
    )
    op.create_table(
        'vorgang_deskriptor',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('vorgang_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column(
            'typ',
            sa.Enum(
                'Freier_Deskriptor',
                'Geograph_Begriffe',
                'Institutionen',
                'Personen',
                'Rechtsmaterialien',
                'Sachbegriffe',
                name='vorgangdeskriptortyp',
            ),
            nullable=False,
        ),
        sa.Column('fundstelle', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(
            ['vorgang_id'],
            ['dip.vorgang.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        schema='dip',
    )
    op.create_table(
        'vorgang_verlinkung',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('vorgang_id', sa.Integer(), nullable=False),
        sa.Column('verweisung', sa.String(), nullable=False),
        sa.Column('titel', sa.String(), nullable=False),
        sa.Column('wahlperiode', sa.Integer(), nullable=False),
        sa.Column('gesta', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(
            ['vorgang_id'],
            ['dip.vorgang.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        schema='dip',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vorgang_verlinkung', schema='dip')
    op.drop_table('vorgang_deskriptor', schema='dip')
    op.drop_table('verkuendung', schema='dip')
    op.drop_table('inkrafttreten', schema='dip')
    op.drop_table('vorgang', schema='dip')
    # ### end Alembic commands ###

    sa.Enum(
        'Freier_Deskriptor',
        'Geograph_Begriffe',
        'Institutionen',
        'Personen',
        'Rechtsmaterialien',
        'Sachbegriffe',
        name='vorgangdeskriptortyp',
    ).drop(op.get_bind(), checkfirst=False)

    sa.Enum('Vorgang', name='vorgangtyp').drop(op.get_bind(), checkfirst=False)
