"""Add Drucksache Tables

Revision ID: a570b683d689
Revises: 8bae05e2bbd2
Create Date: 2023-11-22 21:06:31.795005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a570b683d689'
down_revision: Union[str, None] = '8bae05e2bbd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS dip;')

    op.create_table(
        'drucksache',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('typ', sa.Enum('Dokument', name='dokumenttyp'), nullable=False),
        sa.Column(
            'dokumentart', sa.Enum('Drucksache', name='dokumentartdrucksache'), nullable=False
        ),
        sa.Column('drucksachetyp', sa.String(), nullable=False),
        sa.Column('dokumentnummer', sa.String(), nullable=False),
        sa.Column('wahlperiode', sa.Integer(), nullable=True),
        sa.Column('herausgeber', sa.Enum('BT', 'BR', name='herausgeber'), nullable=False),
        sa.Column('date', sa.String(), nullable=True),
        sa.Column('datum', sa.String(), nullable=False),
        sa.Column('aktualisiert', sa.String(), nullable=False),
        sa.Column('titel', sa.String(), nullable=False),
        sa.Column('autoren_anzahl', sa.Integer(), nullable=False),
        # sa.Column('fundstelle_id', sa.String(), nullable=False, back_populates='drucksache'),
        sa.Column('pdf_hash', sa.String(), nullable=True),
        sa.Column('vorgangsbezug_anzahl', sa.Integer(), nullable=False),
        sa.Column('anlagen', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        schema='dip',
    )
    op.create_table(
        'autor',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('drucksache_id', sa.Integer(), nullable=False),
        sa.Column('titel', sa.String(), nullable=False),
        sa.Column('autor_titel', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(
            ['drucksache_id'],
            ['dip.drucksache.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        schema='dip',
    )
    op.create_table(
        'fundstelle',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('drucksache_id', sa.Integer(), nullable=False),
        sa.Column(
            'dokumentart',
            sa.Enum('Drucksache', 'Plenarprotokoll', name='dokumentart'),
            nullable=False,
        ),
        sa.Column('pdf_url', sa.String(), nullable=True),
        sa.Column('dokumentnummer', sa.String(), nullable=False),
        sa.Column('datum', sa.Date(), nullable=False),
        sa.Column('drucksachetyp', sa.String(), nullable=True),
        sa.Column('herausgeber', sa.Enum('BT', 'BR', 'BV', 'EK', name='zuordnung'), nullable=False),
        sa.Column('urheber', postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column('verteildatum', sa.DateTime(), nullable=True),
        sa.Column('seite', sa.String(), nullable=True),
        sa.Column('anfangsseite', sa.Integer(), nullable=True),
        sa.Column('endseite', sa.Integer(), nullable=True),
        sa.Column('anfangsquadrant', sa.Enum('A', 'B', 'C', 'D', name='quadrant'), nullable=True),
        sa.Column('endquadrant', sa.Enum('A', 'B', 'C', 'D', name='quadrant'), nullable=True),
        sa.Column('frage_nummer', sa.String(), nullable=True),
        sa.Column('anlagen', sa.String(), nullable=True),
        sa.Column('top', sa.Integer(), nullable=True),
        sa.Column('top_zusatz', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(
            ['drucksache_id'],
            ['dip.drucksache.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        schema='dip',
    )
    op.create_table(
        'ressort',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('drucksache_id', sa.Integer(), nullable=False),
        sa.Column('federfuehrend', sa.Boolean(), nullable=False),
        sa.Column('titel', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(
            ['drucksache_id'],
            ['dip.drucksache.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        schema='dip',
    )
    op.create_table(
        'urheber',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('drucksache_id', sa.Integer(), nullable=False),
        sa.Column('einbringer', sa.Boolean(), nullable=True),
        sa.Column('bezeichnung', sa.String(), nullable=False),
        sa.Column('titel', sa.String(), nullable=False),
        sa.Column('rolle', sa.Enum('B', 'U', name='rolle'), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(
            ['drucksache_id'],
            ['dip.drucksache.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        schema='dip',
    )
    op.create_table(
        'vorgangsbezug',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('drucksache_id', sa.Integer(), nullable=False),
        sa.Column('titel', sa.String(), nullable=False),
        sa.Column('vorgangstyp', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(
            ['drucksache_id'],
            ['dip.drucksache.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        schema='dip',
    )
    op.alter_column('example_model', 'name', existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('example_model', 'name', existing_type=sa.VARCHAR(), nullable=False)
    op.drop_table('vorgangsbezug', schema='dip')
    op.drop_table('urheber', schema='dip')
    op.drop_table('ressort', schema='dip')
    op.drop_table('fundstelle', schema='dip')
    op.drop_table('autor', schema='dip')
    op.drop_table('drucksache', schema='dip')
    # ### end Alembic commands ###

    sa.Enum('A', 'B', 'C', 'D', name='quadrant').drop(op.get_bind(), checkfirst=False)
    sa.Enum('BT', 'BR', 'BV', 'EK', name='zuordnung').drop(op.get_bind(), checkfirst=False)
    sa.Enum('Dokument', name='dokumenttyp').drop(op.get_bind(), checkfirst=False)
    sa.Enum('Drucksache', name='dokumentartdrucksache').drop(op.get_bind(), checkfirst=False)
    sa.Enum('BT', 'BR', name='herausgeber').drop(op.get_bind(), checkfirst=False)
    sa.Enum('Drucksache', 'Plenarprotokoll', name='dokumentart').drop(
        op.get_bind(), checkfirst=False
    )
    sa.Enum('B', 'U', name='rolle').drop(op.get_bind(), checkfirst=False)

    op.execute('DROP SCHEMA IF EXISTS dip;')
