"""created_at and updated_at cols

Revision ID: a838547210a6
Revises: 04510c2d194d
Create Date: 2023-11-14 15:20:47.073550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a838547210a6'
down_revision: Union[str, None] = '04510c2d194d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vorgang', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('vorgang', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vorgang', 'updated_at')
    op.drop_column('vorgang', 'created_at')
    # ### end Alembic commands ###
