"""create plenarprotokoll and plenarprotokoll_vorgansbezug table

Revision ID: c30fb340dbe4
Revises: 94b6ec6dbc4d
Create Date: 2023-11-26 19:11:30.427973

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c30fb340dbe4'
down_revision: Union[str, None] = '94b6ec6dbc4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plenarprotokoll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dokumentart', sa.String(), nullable=False),
    sa.Column('typ', sa.String(), nullable=False),
    sa.Column('dokumentnummer', sa.String(), nullable=False),
    sa.Column('wahlperiode', sa.Integer(), nullable=True),
    sa.Column('herausgeber', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('aktualisiert', sa.String(), nullable=False),
    sa.Column('titel', sa.String(), nullable=False),
    sa.Column('pdf_hash', sa.String(), nullable=True),
    sa.Column('vorgangsbezug_anzahl', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plenarprotokoll_vorgangsbezug',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plenarprotokoll_id', sa.Integer(), nullable=True),
    sa.Column('titel', sa.String(), nullable=False),
    sa.Column('abstract', sa.String(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plenarprotokoll_vorgangsbezug')
    op.drop_table('plenarprotokoll')
    # ### end Alembic commands ###
