"""create plenarprotokoll and plenarprotokoll_vorgansbezug table

Revision ID: c30fb340dbe4
Revises: 94b6ec6dbc4d
Create Date: 2023-11-26 19:11:30.427973

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c30fb340dbe4'
down_revision: Union[str, None] = '94b6ec6dbc4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        'plenarprotokoll',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('dokumentart', sa.String(), nullable=False),
        sa.Column('typ', sa.String(), nullable=False),
        sa.Column('dokumentnummer', sa.String(), nullable=False),
        sa.Column('wahlperiode', sa.Integer(), nullable=True),
        sa.Column('herausgeber', sa.String(), nullable=False),
        sa.Column('date', sa.String(), nullable=True),
        sa.Column('datum', sa.Date(), nullable=False),
        sa.Column('aktualisiert', sa.String(), nullable=False),
        sa.Column('titel', sa.String(), nullable=False),
        sa.Column('pdf_hash', sa.String(), nullable=True),
        sa.Column('vorgangsbezug_anzahl', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        schema='dip',
    )
    op.add_column(
        'fundstelle',
        sa.Column('plenarprotokoll_id', sa.Integer(), nullable=True),
        schema='dip',
    )

    op.create_foreign_key(
        'fundstelle_plenarprotokoll_id_fkey',
        'fundstelle',
        'plenarprotokoll',
        ['plenarprotokoll_id'],
        ['id'],
        source_schema='dip',
        referent_schema='dip',
    )

    op.alter_column(
        'vorgangsbezug',
        'drucksache_id',
        nullable=True,
        schema='dip',
    )

    op.add_column(
        'vorgangsbezug',
        sa.Column('vorgang_id', sa.Integer(), nullable=False),
        schema='dip',
    )

    op.add_column(
        'vorgangsbezug',
        sa.Column('plenarprotokoll_id', sa.Integer(), nullable=True),
        schema='dip',
    )

    op.create_foreign_key(
        'vorgangsbezug_plenarprotokoll_id_fkey',
        'vorgangsbezug',
        'plenarprotokoll',
        ['plenarprotokoll_id'],
        ['id'],
        source_schema='dip',
        referent_schema='dip',
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(
        'vorgangsbezug_plenarprotokoll_id_fkey',
        'vorgangsbezug',
        schema='dip',
    )

    op.drop_column('vorgangsbezug', 'plenarprotokoll_id', schema='dip')

    op.drop_column('vorgangsbezug', 'vorgang_id', schema='dip')

    op.alter_column(
        'vorgangsbezug',
        'drucksache_id',
        nullable=False,
        schema='dip',
    )

    op.drop_constraint(
        'fundstelle_plenarprotokoll_id_fkey',
        'fundstelle',
        schema='dip',
    )

    op.drop_column('fundstelle', 'plenarprotokoll_id', schema='dip')

    op.drop_table('plenarprotokoll', schema='dip')
    # ### end Alembic commands ###
