"""create vorgang table

Revision ID: d49dfefbae07
Revises: 8bae05e2bbd2
Create Date: 2023-11-13 18:11:35.707442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd49dfefbae07'
down_revision: Union[str, None] = '8bae05e2bbd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vorgang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typ', sa.String(), nullable=False),
    sa.Column('beratungsstand', sa.String(), nullable=True),
    sa.Column('vorgangstyp', sa.String(), nullable=False),
    sa.Column('wahlperiode', sa.String(), nullable=True),
    sa.Column('initiative', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('datum', sa.Date(), nullable=True),
    sa.Column('aktualisiert', sa.DateTime(), nullable=False),
    sa.Column('titel', sa.String(), nullable=False),
    sa.Column('abstract', sa.String(), nullable=True),
    sa.Column('sachgebiet', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('gesta', sa.String(), nullable=True),
    sa.Column('zustimmungsbeduerftigkeit', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('kom', sa.String(), nullable=True),
    sa.Column('ratsdok', sa.String(), nullable=True),
    sa.Column('inkrafttreten_datum', sa.String(), nullable=True),
    sa.Column('inkrafttreten_erlaeuterung', sa.String(), nullable=True),
    sa.Column('archiv', sa.String(), nullable=True),
    sa.Column('sek', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vorgang_deskriptor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vorgang_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('typ', sa.Enum('FREIER_DESKRIPTOR', 'GEOGRAPH', 'BEGRIFFE', 'INSTITUTIONEN', 'PERSONEN', 'RECHTSMATERIALIEN', 'SACHBEGRIFFE', name='vorgangdeskriptortyp'), nullable=False),
    sa.Column('fundstelle', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['vorgang_id'], ['vorgang.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('example_model', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('example_model', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('vorgang_deskriptor')
    op.drop_table('vorgang')
    # ### end Alembic commands ###
