"""Add abstimmungen table

Revision ID: f8c93790f568
Revises: cd639eb06025
Create Date: 2023-12-06 22:53:46.026322

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f8c93790f568'
down_revision: Union[str, None] = 'cd639eb06025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abstimmung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(), nullable=False),
    sa.Column('abstimmung_datum', sa.Date(), nullable=False),
    sa.Column('akzeptiert', sa.Boolean(), nullable=False),
    sa.Column('ja', sa.Integer(), nullable=False),
    sa.Column('nein', sa.Integer(), nullable=False),
    sa.Column('enthalten', sa.Integer(), nullable=False),
    sa.Column('nicht_abgegeben', sa.Integer(), nullable=False),
    sa.Column('aktualisiert', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
   
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('abstimmung')
    # ### end Alembic commands ###
